monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: swift            
#        grouped:
#            type: group
#            members: [swift, db_handler]
        swift:
            type:       swift_mailer
            from_email: 'contacto@uniestilos.shop'
            to_email:   'esop@live.com'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject: 'uniestilos - Error %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        db_handler:
            # The level of the handler is configured at the same service level: https://github.com/symfony/monolog-bundle/issues/116
            type: service
            id: monolog.db_handler
            channels: ["!event", "!doctrine", "!console"]
